### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by AkashSrinivasan12** [INFO523-S24/project-final-KGCompetitors#1]
The following is the peer review of the project proposal by Daaku Data Singh. The team members that participated in this review are 

- christian ortmann - @christian-ortmann
- Srinivasan Poonkundran - @kANNISTER
- Tejas Bhawari - @tezz-us
- Akash Srinivasan - @AkashSrinivasan12
- Gowtham Theeda - @gowthamtheeda
- Praveen Kumar Pappala - @Praveen-Kumar-Pappala

- Describe the goal of the project.
The existence of PII poses a formidable barrier to the analysis and creation of openly accessible datasets aimed at advancing education, as making such data publicly available exposes students to potential risks. To mitigate these risks, it is imperative to thoroughly screen and cleanse educational data of any PII prior to its public release, a process that could be optimized and facilitated through the application of data science techniques. The goal is unclear in the proposal itself. 

- Describe the data used or collected.
Its nice to see they found a solution to use the large data set through compressing the sample data, consists of around 22,000 essays submitted by students, all of which were written in response to a single assignment prompt, which required students to apply course concepts to a real-world scenario.   

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
There are some detailed tables but there is not enough writings or explanation for analysis plan.  

- Is there anything that is unclear from the proposal?
The description is good but i am not seeing any separate chunk or detail about the Goal of the project.
Its good to see some complex information in the project but it will be more convenient if they provided a gist or something with example about the PII and also Additionally, each label can be prefaced by either B or I but nowhere its not mentioned what is B and I (Explanation / full-form ) 

- Provide constructive feedback on how the team might be able to improve their project.
Some alignments were not so good, The vision of the project is amazing but some technique are unclear and missing in the proposal which add more value to the problem statement.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
The way of explaining the complex problem is impressive and waiting to see how they are gonna use new techniques in the project.  

- Provide constructive feedback on any issues with file and/or code organization.
for loading the dataset over 100 mb in size, they can use GIT LFS (Large file storage) which enable the posibility to use 

- (Optional) Any further comments or feedback?

**Comment by remisublette** [comment]
Thanks for your feedback!
