### ISSUE TITLE
Proposal peer review by Analytical Avengers

### ISSUE THREAD

**Issue by tanyageorge** [INFO523-S24/project-final-KGCompetitors#2]
The following is the peer review of the project proposal by Analytical Avengers. The team members that participated in this review are 

- Sunday Usman - @sundayusman
- Tanya Evita George - @tanyageorge
- Mellika Akbarsharifi - @mellica97
- Divya Liladhar Dhole - @Divyadhole
- Mohammad Ali Farmani - @mfarmani95
- H M Abdul Fattah - @hmfattah
- Gabriel Gedaliah Geffen - @gabegef

- Describe the goal of the project.

The goal is to make a model that can detect any personal information i.e. PII mentioned in student's writings or essays.

- Describe the data used or collected.

The dataset is a .zip file called 'essays.zip' and it consists of the student's personal and contact information.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

 There is no analysis plan mentioned for the questions. Unclear on how your team will proceed for each question. While you have explained it in Plan of Attack, it would help if you could explain it under the heading 'Analysis'.

- Is there anything that is unclear from the proposal?

1. The goal is not clear and this line is rather contradictory like mentioned in the first paragraph where it says "The existence of PII poses a formidable barrier to the analysis and creation of openly accessible datasets aimed at advancing education, as making such data publicly available exposes students to potential risks."
2. The dimensions of the dataset have not been mentioned.

- Provide constructive feedback on how the team might be able to improve their project.

1. The goal of the project could be described more clearly.
2. Describing the dataset with its dimensions could give a better insight into how big or vast your dataset is. 
3. Like you have mentioned that each label can be prefaced by a B or an I, would help to elaborate what B or I stands for or if they are a variable that will be used.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

Looking forward to seeing what kind of data is personal and how the team is able to detect bits of personal information from student's essays and how the project could help keep a student's privacy intact and prevent any unnecessary leaking of personal information.

- Provide constructive feedback on any issues with file and/or code organization.

1. The histogram plot could've been summarized in just words instead of a whole plot as it is confusing to understand the workflow of the project.
2. The table for random samples of data is vague and have not been given proper headings for each column such that one can understand at a glimpse.

- (Optional) Any further comments or feedback?

The repo organisation and Plan of Attack is very well organized and neatly explained. The goal of your project is quite ethical and something a lot of people would easily overlook while it can be dangerous. The results of your project could truly help mitigate this danger so good luck!

**Comment by remisublette** [comment]
Thanks for your feedback!
