### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by tezz-us** [INFO523-S24/project-final-KGCompetitors#4]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

christian ortmann - @christian-ortmann

Srinivasan Poonkundran - @kANNISTER

Tejas Bhawari - @tezz-us

RAJITHA REDDY TIRUTHANI - @RAJITHAREDDYTIRUTHANI

Akash Srinivasan - @AkashSrinivasan12

Gowtham Theeda - @gowthamtheeda

Praveen Kumar Pappala - @Praveen-Kumar-Pappala

- Content: Is the research question well designed and is the data being used relevant to the research question?
Yes !! Addressing a practical problem by focusing on the detection of personally identifiable information in student writing, Which is relevant and important for protecting student privacy in educational dataset.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?
The cat eye plot is explained well, but the visualization itself is a bit lack luster. Labels could be more descriptive for connecting each unit. The plotly bar chart is a nice touch with the interactive aspects, but for presentation's purpose, there should be annotations of the values themselves.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?
Yes, but the methodology could have been better, it seems they went over the project very quickly and could have given a more detailed methodology of how they built the model. It seems like a good amount of time went into the presentation.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?
Yes, refer to comments in the content section.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?
The group delivered an excellent presentation, providing comprehensive content on their slides that effectively explained the project's concept and results.

**Comment by remisublette** [comment]
Thanks for your feedback!
