### ISSUE TITLE
Code peer review by Analytical Avengers

### ISSUE THREAD

**Issue by tanyageorge** [INFO523-S24/project-final-KGCompetitors#6]
The following is the peer review of the project code by Analytical Avengers. The team members that participated in this review are 

- Sunday Usman - @sundayusman
- Tanya Evita George - @tanyageorge
- Mellika Akbarsharifi - @mellica97
- Divya Liladhar Dhole - @Divyadhole
- Mohammad Ali Farmani - @mfarmani95
- H M Abdul Fattah - @hmfattah
- Gabriel Gedaliah Geffen - @gabegef
---

#### 1. Purpose of Code
- [X] Clearly defined and understood
- [ ] Ambiguous or unclear

---

#### 2. Code Quality

- [X] Code is clean, readable, and well-organized
- [ ] Adequate comments explaining complex or tricky code sections
- [X] Variables, methods, and classes have meaningful names
- [X] Consistent code style (indentation, naming conventions, etc.)

---

#### 3. Functionality

- [X] Code functions as intended and produces the expected outcome
- [X] Edge cases have been considered and handled
- [X] No obvious bugs or issues found

---

#### 4. Testing

- [X] Adequate unit tests covering key functionality
- [ ] Tests are clear and can be easily understood
- [X] All tests pass successfully

---

#### 5. Documentation

- [ ] Code documentation (e.g., docstrings, comments) is sufficient
- [ ] Readme or other documentation updated if necessary

---

#### 6. Best Practices

- [ ] No hardcoded values; constants used appropriately
- [X] Security and privacy concerns addressed (e.g., no sensitive data exposed)
- [X] Code avoids repetition and promotes reusability

---

#### 7. Additional Comments

- Please provide feedback, areas of improvement, or other observations.

There are almost no comments  and its pretty very high-level data so adding them would help understand the code better. 
It is also a little difficult to identify the source data and where the model fine-tuning takes place.
The explanation of why specific DeBERTa models were chosen is somewhat superficial. Including more technical details about the advantages of each model size, such as computational efficiency, memory usage, or specific features of the DeBERTa architecture that benefit PII detection, could provide a more compelling justification for your choices.
---

#### 8. Recommendation

- [ ] Approved - ready to be merged
- [X] Approved with minor issues - can be addressed later
- [ ] Requires changes - provide feedback and request another review

---

**Comment by xinformatics** [comment]
The code is provided in the analysis folder which contains detailed jupyter notebooks for all the three models.

**Comment by remisublette** [comment]
Thanks for your feedback!
